# Generated by Django 3.2.4 on 2021-07-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nomComp', models.CharField(max_length=40, verbose_name='Nombre')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='Numero telefono')),
                ('contrasenia', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
    ]
